version: "3.8"

networks:
  microservice:
    driver: bridge
    name: microservice
  mongodb:
    driver: bridge
    name: mongodb

volumes:
  mongo_data:

services:
  mongo:
    restart: unless-stopped
    image: mongo:6.0.2
    networks:
      - mongodb
      - microservice
    container_name: ${PROJECT_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  mongo-express:
    image: mongo-express
    tty: true
    container_name: ${PROJECT_NAME}-express
    networks:
      - mongodb
    restart: unless-stopped
    depends_on:
      - mongo
    profiles:
      - dev
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
#      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
#      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@${PROJECT_NAME}:27017/